//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_B_isTovar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekat_B_isTovar.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziro racun.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj firmu.
        /// </summary>
        internal static string AddCompanyTitle {
            get {
                return ResourceManager.GetString("AddCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj odredište.
        /// </summary>
        internal static string AddDestination {
            get {
                return ResourceManager.GetString("AddDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj izvorište.
        /// </summary>
        internal static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj turu.
        /// </summary>
        internal static string AddTour {
            get {
                return ResourceManager.GetString("AddTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kamion.
        /// </summary>
        internal static string AddTruck {
            get {
                return ResourceManager.GetString("AddTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dolaska.
        /// </summary>
        internal static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme dolaska.
        /// </summary>
        internal static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodijeli.
        /// </summary>
        internal static string AssignButton {
            get {
                return ResourceManager.GetString("AssignButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodijeli prikolicu.
        /// </summary>
        internal static string AssignTrailer {
            get {
                return ResourceManager.GetString("AssignTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodjeli prikolice..
        /// </summary>
        internal static string AssignTrailerError {
            get {
                return ResourceManager.GetString("AssignTrailerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupnost.
        /// </summary>
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupan.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plava.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brend.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće obrisati vozača zbog njegovih dodjela. Molimo riješite to prvo..
        /// </summary>
        internal static string CantDeleteDriver {
            get {
                return ResourceManager.GetString("CantDeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne možete obrisati ovu prikolicu jer je već zadužena. Oslobodite ju prije brisanja!.
        /// </summary>
        internal static string CantDeleteTrailer {
            get {
                return ResourceManager.GetString("CantDeleteTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosivost.
        /// </summary>
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosivost mora biti broj!.
        /// </summary>
        internal static string CapacityError {
            get {
                return ResourceManager.GetString("CapacityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas odaberite vozača za brisanje..
        /// </summary>
        internal static string ChooseDeleteDriver {
            get {
                return ResourceManager.GetString("ChooseDeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite prikolicu za brisanje..
        /// </summary>
        internal static string ChooseDeleteTrailer {
            get {
                return ResourceManager.GetString("ChooseDeleteTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite problem za izmjenu..
        /// </summary>
        internal static string ChooseIssueEdit {
            get {
                return ResourceManager.GetString("ChooseIssueEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izabrani vozač:.
        /// </summary>
        internal static string ChoosenDriver {
            get {
                return ResourceManager.GetString("ChoosenDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas odaberite vozača iz tabele..
        /// </summary>
        internal static string ChooseSelectDriver {
            get {
                return ResourceManager.GetString("ChooseSelectDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite kamion za brisanje!.
        /// </summary>
        internal static string ChooseTruckDelete {
            get {
                return ResourceManager.GetString("ChooseTruckDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi i kamion i prikolicu..
        /// </summary>
        internal static string ChooseTruckTrailer {
            get {
                return ResourceManager.GetString("ChooseTruckTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očisti.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma dodana.
        /// </summary>
        internal static string CompanyAdded {
            get {
                return ResourceManager.GetString("CompanyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju firmi..
        /// </summary>
        internal static string CompanyLoadError {
            get {
                return ResourceManager.GetString("CompanyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv firme.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završeno.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri konekciji..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci uspješno ažurirani..
        /// </summary>
        internal static string DataChanged {
            get {
                return ResourceManager.GetString("DataChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri konekciji.
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda brisanja.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme polaska mora biti prije vremena dolaska..
        /// </summary>
        internal static string DepartureArrivalWarning {
            get {
                return ResourceManager.GetString("DepartureArrivalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum polaska.
        /// </summary>
        internal static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme polaska.
        /// </summary>
        internal static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma odredišta.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odredište uspješno dodano..
        /// </summary>
        internal static string DestinationAdded {
            get {
                return ResourceManager.GetString("DestinationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firme odredišta.
        /// </summary>
        internal static string DestinationCompanies {
            get {
                return ResourceManager.GetString("DestinationCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite sva polja za odredište..
        /// </summary>
        internal static string DestinationFields {
            get {
                return ResourceManager.GetString("DestinationFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispečer.
        /// </summary>
        internal static string Dispatcher {
            get {
                return ResourceManager.GetString("Dispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Dispečera.
        /// </summary>
        internal static string DispatcherId {
            get {
                return ResourceManager.GetString("DispatcherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime dispečera.
        /// </summary>
        internal static string DispatcherName {
            get {
                return ResourceManager.GetString("DispatcherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vozač.
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška provjere dostupnosti vozača.
        /// </summary>
        internal static string DriverAvailabilityError {
            get {
                return ResourceManager.GetString("DriverAvailabilityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vozač obrisan..
        /// </summary>
        internal static string DriverDeleted {
            get {
                return ResourceManager.GetString("DriverDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri brisanju vozača..
        /// </summary>
        internal static string DriverDeleteError {
            get {
                return ResourceManager.GetString("DriverDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite obrisati odabranog vozača?.
        /// </summary>
        internal static string DriverDeleteSure {
            get {
                return ResourceManager.GetString("DriverDeleteSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o vozaču uspješno promijenjeni..
        /// </summary>
        internal static string DriverEdited {
            get {
                return ResourceManager.GetString("DriverEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri izmjeni podataka vozača..
        /// </summary>
        internal static string DriverEditError {
            get {
                return ResourceManager.GetString("DriverEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Vozača.
        /// </summary>
        internal static string DriverID {
            get {
                return ResourceManager.GetString("DriverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju vozača..
        /// </summary>
        internal static string DriverLoadError {
            get {
                return ResourceManager.GetString("DriverLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime vozača.
        /// </summary>
        internal static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vozači.
        /// </summary>
        internal static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri odabiru vozača..
        /// </summary>
        internal static string DriverSelectionError {
            get {
                return ResourceManager.GetString("DriverSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vozača.
        /// </summary>
        internal static string DriversList {
            get {
                return ResourceManager.GetString("DriversList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite kamion za izmjenu..
        /// </summary>
        internal static string EditChooseTruck {
            get {
                return ResourceManager.GetString("EditChooseTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena problema.
        /// </summary>
        internal static string EditIssue {
            get {
                return ResourceManager.GetString("EditIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi rutu.
        /// </summary>
        internal static string EditRoute {
            get {
                return ResourceManager.GetString("EditRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi turu.
        /// </summary>
        internal static string EditTour {
            get {
                return ResourceManager.GetString("EditTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni prikolicu.
        /// </summary>
        internal static string EditTrailer {
            get {
                return ResourceManager.GetString("EditTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID korisnika mora biti validan pozitivan broj..
        /// </summary>
        internal static string EditUserId {
            get {
                return ResourceManager.GetString("EditUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite sva obavezna polja!.
        /// </summary>
        internal static string EmptyCompanyFields {
            get {
                return ResourceManager.GetString("EmptyCompanyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne možete ostaviti prazno.
        /// </summary>
        internal static string EmptyErrorMessage {
            get {
                return ResourceManager.GetString("EmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime i lozinku.
        /// </summary>
        internal static string EmptyLoginFields {
            get {
                return ResourceManager.GetString("EmptyLoginFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite sva obavezna polja!.
        /// </summary>
        internal static string EmptyRegisterFields {
            get {
                return ResourceManager.GetString("EmptyRegisterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo popunite sva polja..
        /// </summary>
        internal static string EnterAllFields {
            get {
                return ResourceManager.GetString("EnterAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ukupnu cijenu.
        /// </summary>
        internal static string EnterFinalPrice {
            get {
                return ResourceManager.GetString("EnterFinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite status.
        /// </summary>
        internal static string EnterStatus {
            get {
                return ResourceManager.GetString("EnterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri izmjeni problema..
        /// </summary>
        internal static string ErrorEditProblem {
            get {
                return ResourceManager.GetString("ErrorEditProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupna cijena.
        /// </summary>
        internal static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorivo.
        /// </summary>
        internal static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konjske snage.
        /// </summary>
        internal static string HorsePower {
            get {
                return ResourceManager.GetString("HorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sati.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konjske snage moraju biti broj..
        /// </summary>
        internal static string HpError {
            get {
                return ResourceManager.GetString("HpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Prikolice.
        /// </summary>
        internal static string IdTrailer {
            get {
                return ResourceManager.GetString("IdTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U toku.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravno korisničko ime ili lozinka!.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je zauzet u tom vremenskom periodu..
        /// </summary>
        internal static string IsBusy {
            get {
                return ResourceManager.GetString("IsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis problema.
        /// </summary>
        internal static string IssueDescription {
            get {
                return ResourceManager.GetString("IssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemi.
        /// </summary>
        internal static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemi.
        /// </summary>
        internal static string IssuesTitle {
            get {
                return ResourceManager.GetString("IssuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta.
        /// </summary>
        internal static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenca.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dozvole.
        /// </summary>
        internal static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registarska oznaka.
        /// </summary>
        internal static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svijetla.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisi i održavanje.
        /// </summary>
        internal static string MaintenanceTitle {
            get {
                return ResourceManager.GetString("MaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometraža.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometraža mora biti broj..
        /// </summary>
        internal static string MileageError {
            get {
                return ResourceManager.GetString("MileageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moj profil.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje ture.
        /// </summary>
        internal static string MyTours {
            get {
                return ResourceManager.GetString("MyTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moja prikolica.
        /// </summary>
        internal static string MyTrailer {
            get {
                return ResourceManager.GetString("MyTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moj kamion.
        /// </summary>
        internal static string MyTruck {
            get {
                return ResourceManager.GetString("MyTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemaš nalog?.
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema tura.
        /// </summary>
        internal static string NoTours {
            get {
                return ResourceManager.GetString("NoTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema podataka o prikolici..
        /// </summary>
        internal static string NoTrailerData {
            get {
                return ResourceManager.GetString("NoTrailerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema podataka o kamionu..
        /// </summary>
        internal static string NoTruckData {
            get {
                return ResourceManager.GetString("NoTruckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodne ture.
        /// </summary>
        internal static string PastTours {
            get {
                return ResourceManager.GetString("PastTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas unesite validnog vozača..
        /// </summary>
        internal static string PleaseValidDriver {
            get {
                return ResourceManager.GetString("PleaseValidDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas unesite validnu cijenu..
        /// </summary>
        internal static string PleaseValidPrice {
            get {
                return ResourceManager.GetString("PleaseValidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas unesite sve validne vrijednosti za vremena..
        /// </summary>
        internal static string PleaseValidTime {
            get {
                return ResourceManager.GetString("PleaseValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas odaberite vozača..
        /// </summary>
        internal static string PlsChooseDriver {
            get {
                return ResourceManager.GetString("PlsChooseDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas odaberite prikolicu za izmjenu..
        /// </summary>
        internal static string PlsChooseTrailer {
            get {
                return ResourceManager.GetString("PlsChooseTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštanski broj.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem uspješno izmijenjen..
        /// </summary>
        internal static string ProblemEdited {
            get {
                return ResourceManager.GetString("ProblemEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst problema ne može biti prazan..
        /// </summary>
        internal static string ProblemText {
            get {
                return ResourceManager.GetString("ProblemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina proizvodnje.
        /// </summary>
        internal static string ProductionYear {
            get {
                return ResourceManager.GetString("ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj se.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija uspješna!.
        /// </summary>
        internal static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi problem.
        /// </summary>
        internal static string ReportIssue {
            get {
                return ResourceManager.GetString("ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspored tura.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi.
        /// </summary>
        internal static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi firmu.
        /// </summary>
        internal static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite datum.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi vozača.
        /// </summary>
        internal static string SelectDriver {
            get {
                return ResourceManager.GetString("SelectDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi turu.
        /// </summary>
        internal static string SelectTour {
            get {
                return ResourceManager.GetString("SelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisi i održavanje.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma izvorišta.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvorište uspješno dodano..
        /// </summary>
        internal static string SourceAdded {
            get {
                return ResourceManager.GetString("SourceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firme izvorišta.
        /// </summary>
        internal static string SourceCompanies {
            get {
                return ResourceManager.GetString("SourceCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite sva polja za firmu izvorišta..
        /// </summary>
        internal static string SourceFields {
            get {
                return ResourceManager.GetString("SourceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno obavljeno.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj prikolicu.
        /// </summary>
        internal static string TabAddTrailer {
            get {
                return ResourceManager.GetString("TabAddTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura.
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura je uspješno dodana..
        /// </summary>
        internal static string TourAdded {
            get {
                return ResourceManager.GetString("TourAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji ture.
        /// </summary>
        internal static string TourDetails {
            get {
                return ResourceManager.GetString("TourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dohvatanju ture..
        /// </summary>
        internal static string TourGetError {
            get {
                return ResourceManager.GetString("TourGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju ture..
        /// </summary>
        internal static string TourLoadError {
            get {
                return ResourceManager.GetString("TourLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ture.
        /// </summary>
        internal static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolica.
        /// </summary>
        internal static string Trailer {
            get {
                return ResourceManager.GetString("Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolica uspješno dodana..
        /// </summary>
        internal static string TrailerAdded {
            get {
                return ResourceManager.GetString("TrailerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodavanju prikolice..
        /// </summary>
        internal static string TrailerAddError {
            get {
                return ResourceManager.GetString("TrailerAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolica uspješno dodijeljena..
        /// </summary>
        internal static string TrailerAssigned {
            get {
                return ResourceManager.GetString("TrailerAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolica obrisana!.
        /// </summary>
        internal static string TrailerDeleted {
            get {
                return ResourceManager.GetString("TrailerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri brisanju prikolice..
        /// </summary>
        internal static string TrailerDeleteError {
            get {
                return ResourceManager.GetString("TrailerDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite obrisati odabranu prikolicu?.
        /// </summary>
        internal static string TrailerDeleteSure {
            get {
                return ResourceManager.GetString("TrailerDeleteSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolica uspješno izmijenjena..
        /// </summary>
        internal static string TrailerEdited {
            get {
                return ResourceManager.GetString("TrailerEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri izmjeni prikolice..
        /// </summary>
        internal static string TrailerEditError {
            get {
                return ResourceManager.GetString("TrailerEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o prikolici.
        /// </summary>
        internal static string TrailerInfo {
            get {
                return ResourceManager.GetString("TrailerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju prikolica..
        /// </summary>
        internal static string TrailerLoadError {
            get {
                return ResourceManager.GetString("TrailerLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolice.
        /// </summary>
        internal static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikolice.
        /// </summary>
        internal static string TrailersList {
            get {
                return ResourceManager.GetString("TrailersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamion.
        /// </summary>
        internal static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamion uspješno dodan..
        /// </summary>
        internal static string TruckAdded {
            get {
                return ResourceManager.GetString("TruckAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite obrisati kamion?.
        /// </summary>
        internal static string TruckConfirmDelete {
            get {
                return ResourceManager.GetString("TruckConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamion obrisan.
        /// </summary>
        internal static string TruckDeleted {
            get {
                return ResourceManager.GetString("TruckDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri brisanju kamiona..
        /// </summary>
        internal static string TruckDeleteError {
            get {
                return ResourceManager.GetString("TruckDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamion uspješno izmijenjen..
        /// </summary>
        internal static string TruckEdited {
            get {
                return ResourceManager.GetString("TruckEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri izmjeni kamiona..
        /// </summary>
        internal static string TruckEditError {
            get {
                return ResourceManager.GetString("TruckEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID kamiona.
        /// </summary>
        internal static string TruckId {
            get {
                return ResourceManager.GetString("TruckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o kamionu.
        /// </summary>
        internal static string TruckInfo {
            get {
                return ResourceManager.GetString("TruckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju kamiona.
        /// </summary>
        internal static string TruckLoadError {
            get {
                return ResourceManager.GetString("TruckLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamioni.
        /// </summary>
        internal static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamioni.
        /// </summary>
        internal static string TrucksList {
            get {
                return ResourceManager.GetString("TrucksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedostupan.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepoznat.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predstojeće ture.
        /// </summary>
        internal static string UpcomingTours {
            get {
                return ResourceManager.GetString("UpcomingTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Korisnika.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, Dispečer!.
        /// </summary>
        internal static string WelcomeDispatcher {
            get {
                return ResourceManager.GetString("WelcomeDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, Vozač!.
        /// </summary>
        internal static string WelcomeDriver {
            get {
                return ResourceManager.GetString("WelcomeDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina proizvodnje mora biti broj..
        /// </summary>
        internal static string YpError {
            get {
                return ResourceManager.GetString("YpError", resourceCulture);
            }
        }
    }
}
